### ISSUE TITLE
Integration with attendance module

### ISSUE THREAD

**Issue by frflores11** [NaN-tic/trytond-payroll#1]
Hi Guys!.. have you considered to integrate this module with the new attendance module? theoretically the information provided by the attendance module should be used to compute the payroll, or do you consider that the nature of the information is different?

Thank you in advance!,

**Comment by albertca** [comment]
It is possible that working shifts could be replaced by the equivalent concept in attendance module, though we have no plans for working on that at the moment.

**Comment by frflores11** [comment]
Thank you Albert!,
